tasks:
  - name: terraform
    before: |
      cd /workspace/terraform-begginer-bootcamp-2023
      cd .bin
      source set_tf_alias
      source generate_tfrc_credentials 
      source install_terraform_cli.sh
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      cd /workspace/terraform-begginer-bootcamp-2023
      cd .bin
      source set_tf_alias 
      source generate_tfrc_credentials 
      source install_aws_cli
vscode:
  extensions:
    - amazonwebservices.aws-toolkit-vscode
    - hashicorp.terraform
