tasks:
  - name: terraform
    before: |
      cd /workspace/terraform-begginer-bootcamp-2023
      cd .bin
      source install_terraform_cli.sh 
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |

      rm --force "/workspace/awscliv2.zip"
      rm -rf '/workspace/aws'
      cd /workspace/terraform-begginer-bootcamp-2023
      cd .bin
      source install_aws_cli 
vscode:
  extensions:
    - amazonwebservices.aws-toolkit-vscode
    - hashicorp.terraform
