#!/usr/bin/env bash

# Check if the TERRAFORM_CLOUD_TOKEN environment variable is set
if [ -z "$TERRAFORM_CLOUD_TOKEN" ]; then
    echo "TERRAFORM_CLOUD_TOKEN environment variable is not set. Please set it."
    exit 1
fi

# Directory where the credentials.tfrc.json file should be located
credentials_dir="/home/gitpod/.terraform.d/credentials/tfrc"

# Create the directory if it doesn't exist
mkdir -p "$credentials_dir"

# JSON structure for credentials.tfrc.json
json_content=$(cat <<EOF
{
  "credentials": {
    "your_organization": {
      "token": "$TERRAFORM_CLOUD_TOKEN"
    }
  }
}
EOF
)

# Write the JSON content to credentials.tfrc.json in the specified directory
echo "$json_content" > "$credentials_dir/credentials.tfrc.json"

echo "credentials.tfrc.json file generated in $credentials_dir with the specified JSON structure."