#!/usr/bin/env bash

# Define the alias you want to add
alias_to_add="alias tf=\"terraform\""

# Check if .bash_profile exists, if not create it
if [ ! -f ~/.bash_profile ]; then
    touch ~/.bash_profile
fi

# Check if the alias is already defined in .bash_profile
if ! grep -q "alias tf=\"terraform\"" ~/.bash_profile; then
    # If the alias is not defined, add it to .bash_profile
    echo "$alias_to_add" >> ~/.bash_profile
    echo "Alias 'tf' added to .bash_profile."
else
    echo "Alias 'tf' already exists in .bash_profile."
fi

# Source the .bash_profile to make the alias effective in the current session
source ~/.bash_profile