#!/usr/bin/env bash

# Define the alias
alias_line="alias tf=\"terraform\""

# Check if .bash_profile exists, if not create it
if [ ! -f ~/.bash_profile ]; then
    touch ~/.bash_profile
fi

# Check if the alias is already defined in .bash_profile
if ! grep -q "$alias_line" ~/.bash_profile; then
    # If the alias is not defined, add it to .bash_profile
    echo "$alias_line" >> ~/.bash_profile
    echo "Alias 'tf' added to .bash_profile."
else
    echo "Alias 'tf' already exists in .bash_profile."
fi
